CREATE TABLE USUARIOS3PTC(
UUID_Usuario VARCHAR2(50) PRIMARY KEY,
correoElectronico VARCHAR2(100) NOT NULL UNIQUE,
contrasena VARCHAR2(255) NOT NULL
);

DROP TABLE USUARIOS3PTC

commit

select * from USUARIOS3PTC